WITH CTE_SOURCE AS (
  SELECT COL1, COL2, COL3
  FROM TABLE_A
)

, CTE_GROUP AS (
  SELECT COL1, SUM(COL2), MAX(COL3)
  FROM CTE_SOURCE
)

, CTE_SOURCE_2 AS (
  SELECT COL4, COL5
  FROM TABLE_B
)

, CTE_JOIN AS (
  SELECT COL1, COL2, COL3, COL5
  FROM CTE_GROUP AS A
  INNER JOIN CTE_SOURCE_2 AS B
  ON COL4 = COL1
)

, CTE_FILTER AS (
  SELECT *
  FROM CTE_JOIN
  WHERE COL5 >= 100
)

, CTE_SOURCE_3 AS (
  SELECT *
  FROM TABLE_C
)

, CTE_JOIN_2 AS (
  SELECT COL1, COL2, COL3, COL5, COL7
  FROM CTE_FILTER AS A
  LEFT JOIN CTE_SOURCE_3 AS B
  ON COL6 = COL1
)

SELECT COL1, COL2, COL3, COL4
FROM CTE_FILTER;